
//#ifndef _CUSTOM_CONFIG_
//#define _CUSTOM_CONFIG_

#include "k_custom_config.h"

//#define UART_DEBUG_ENABLE
#ifdef UART_DEBUG_ENABLE
#define MAIN_UART_DEBUG
//#define MISC_UART_DEBUG
//#define FM_UART_DEBUG

#define BAT_UART_DEBUG
//#define BLUETOOTH_UART_DEBUG

//#define IR_UART_DEBUG
//#define ADKEY_UART_DEBUG

//#define UART_DEBUG_AT_P06P07
#define UART_DEBUG_AT_P24P25
//#define UART_DEBUG_AT_P36P37
#endif

#define USE_AUTO_SELECT_EEPROM_RTC_MEM

//#define USE_MANUAL_IDLE_FUNC
//#define KEY_TONE_INDICATOR_ENABLE

//#define EVENT_50MS_HANDLER_ENABLE

//#define BLUE_TOOTH_MODE_ENABLE

//#define BLUE_TOOTH_UART_FUNC
//#define USE_POWER_KEY
//#define MUTE_GPIO_USE_P03
//#define NO_PLAY_STATUS_LED

//#define AUX_DETECTION_THREAD_ENABLE
//#define AUX_DETECT_USE_P01

//#define PHONE_DETECTION_THREAD_ENABLE
//#define PHONE_DETECT_USE_P04


//#define USE_BAT_MANAGEMENT
//#define CHARGER_DETECTION_THREAD_ENABLE
//#define CHARGER_DETECT_USE_P01
//#define BAT_MEASURE_USE_ADC_PORT
//#define BAT_AD_GPIO_USE_P05

//#define ADKEY_GPIO_USE_P02
//#define IIC_GPIO_CLK_DATA_USE_P00_P01
//#define AUX_DETECTION_THREAD_ENABLE
//#define PHONE_DETECTION_THREAD_ENABLE
//#define AUX_DETECT_USE_P01

//#define JK_TEST_PROJECT

#ifdef JK_TEST_PROJECT
#define MUTE_GPIO_USE_P02
#define NO_PLAY_STATUS_LED

#define IIC_GPIO_CLK_DATA_DUMMY
#define ADKEY_GPIO_USE_P06

#define AD_DETECT_FUNC
#define USE_ADKEY_DETECT_HP
#define USE_ADKEY_DETECT_AUX

#endif

//#define JK_GHD_803A_1096A_V001
//#define JK_HYH_WM2428B_1096A_V001
//#define JK_HYH_QX3_7C_1082A_V001
//#define JK_IBT40_1094A_V001
//#define JK_NS_14FB_1094A_V001
//#define JK_IBT_388_1096A_V001
//#define JK_SM_001_1096A_V001

#ifdef JK_GHD_803A_1096A_V001

//#define SYS_OSC_USE_ONCHIP_HTC

#define MUTE_GPIO_USE_DUMMY

#define IIC_GPIO_CLK_DATA_USE_P00_P01
#define ADKEY_GPIO_USE_P07

#define PLAY_STATUS_LED_P26

#define NOT_USE_LINE_IN_FUNC


//#define USE_POWER_KEY
#define POWER_CTRL_GPIO_USE_P02

#define USE_BAT_MANAGEMENT
#define CHARGER_DETECTION_THREAD_ENABLE
#define CHARGER_DETECT_USE_P04
#define BAT_MEASURE_USE_ADC_PORT
#define BAT_AD_GPIO_USE_P05
#define DISABLE_P05_OSC_OUTPUT

#define BAT_CHARGER_IND_HLDR
#define BAT_CHARGE_LED_IND
#define BAT_CHARGE_LED_IND_AT_P27

#define BAT_LOW_LEVEL_HLDR
#define BAT_LOW_BEEP_ALERT

#endif


#ifdef JK_HYH_WM2428B_1096A_V001
#define IIC_GPIO_CLK_DATA_DUMMY
#define ADKEY_GPIO_USE_P07

#define MUTE_GPIO_USE_P27
//#define MUTE_CTRL_LEVEL_LOW_MUTE
#define NO_PLAY_STATUS_LED
#define DEFAULT_VOL_AT_POWER_ON	30
#define NOT_USE_LINE_IN_FUNC
#define NOT_DISPLAY_SCAN
#endif


#ifdef JK_HYH_QX3_7C_1082A_V001

#define SYS_OSC_USE_ONCHIP_HTC
#define IIC_GPIO_CLK_DATA_USE_P00_P01
#define ADKEY_GPIO_USE_P02
#define AC1082_ADKEY_AT_P02

#define NO_DEVICE_DEFAULT_IDLE_MODE
#define PLAY_STATUS_LED_P46
#define LED_CTRL_LEVEL_LOW_ON

#define MUTE_GPIO_USE_DUMMY
#define NOT_USE_LINE_IN_FUNC
#define NOT_DISPLAY_SCAN
#define NO_FM_CHIP_ON_BOARD
#define USE_EEPROM_MEMORY 
#define DEFAULT_VOL_AT_POWER_ON	30

#endif


#ifdef JK_IBT40_1094A_V001

#define SYS_OSC_USE_ONCHIP_HTC
#define IIC_GPIO_CLK_DATA_DUMMY
#define ADKEY_GPIO_USE_P02

#define MUTE_GPIO_USE_P05

#define PLAY_STATUS_LED_P46
#define LED_CTRL_LEVEL_LOW_ON

#define NOT_USE_LINE_IN_FUNC
#define NOT_DISPLAY_SCAN

#define USB_ERP2_FUNC
#define BLUE_TOOTH_ERP2_FUNC
#define ERP2_TIMER_UNIT_IN_MIN	3
#define USE_BT_PHONE_KEY_SHORT_WAKEUP_IDLE

//#define NOT_MOUNT_USB_FUNC

#define BLUE_TOOTH_CELLPHONE_FUNC
#define BLUE_TOOTH_UART_BAUDRATE_AT_9600
#define BLUE_TOOTH_CONFIG_DEV_NAME
#define BLUE_TOOTH_MODE_ENABLE
#define BLUE_TOOTH_UART_FUNC
#define BLUE_TOOTH_UART_AT_P24P25
#define BLUE_TOOTH_STATUS_LED_AT_P17
#define BLUE_TOOTH_CALL_STATUS_AT_P16
#define BLUE_TOOTH_STATUS_LED_PARTTERN
#define SYS_POWER_ON_FORCE_IN_BT_MODE

#define BLUE_TOOTH_GPIO_PWR_AT_P01
#endif

#ifdef JK_NS_14FB_1094A_V001

#define SYS_OSC_USE_ONCHIP_HTC
#define IIC_GPIO_CLK_DATA_DUMMY
#define ADKEY_GPIO_USE_P02

#define MUTE_GPIO_USE_P05

#define PLAY_STATUS_LED_P01
#define LED_CTRL_LEVEL_LOW_ON

#define NOT_USE_LINE_IN_FUNC
#define NOT_DISPLAY_SCAN

#define USE_POWER_IDLE_MODE

#define DEFAULT_VOL_AT_POWER_ON	30

#if 1
#define BLUE_TOOTH_MODE_ENABLE
#define BLUE_TOOTH_UART_FUNC
#define BLUE_TOOTH_UART_AT_P24P25
#define BLUE_TOOTH_GPIO_FUNC
#define BLUE_TOOTH_GPIO_PWR_AT_P16
#endif

#endif


#ifdef JK_IBT_388_1096A_V001

#define SYS_OSC_USE_ONCHIP_HTC
//#define IIC_GPIO_CLK_DATA_USE_P00_P01
#define IIC_GPIO_CLK_DATA_USE_P01_P00
#define ADKEY_GPIO_USE_P07

#define MUTE_GPIO_USE_P02

#define PLAY_STATUS_LED_P04
#define LED_CTRL_LEVEL_LOW_ON

#define NOT_DISPLAY_SCAN

#define FM_AUX_SHARE_SAME_PATH

#define CUSTOM_DEFINED_PATH

#define AUX_DETECTION_THREAD_ENABLE
#define AUX_DETECT_USE_P01
#define AUX_DETECTION_GPIO_SHARE_WITH_IIC_CLK

#define USE_POWER_IDLE_MODE
#define AMP_GPIO_SEL_AB_D_MODE
#define AMP_GPIO_SEL_AB_D_MODE_AT_P46

//#define USE_POWER_KEY
//#define POWER_CTRL_GPIO_USE_P05
#define DISABLE_P05_OSC_OUTPUT

#define NOT_USE_IR_FUNC


#if 1
#define USE_MODE_ANSWER_PHONE
#define BLUE_TOOTH_MODE_ENABLE
#define BLUE_TOOTH_UART_FUNC
#define BLUE_TOOTH_UART_AT_P24P25
#define BLUE_TOOTH_UART_BAUDRATE_AT_9600
#define BLUE_TOOTH_CONFIG_DEV_NAME
#define BLUE_TOOTH_CELLPHONE_FUNC
#define BLUE_TOOTH_STATUS_LED_AT_P05

#define NOT_MOUNT_USB_FUNC
#define BLUE_TOOTH_GPIO_PWR_AT_P36

#define BLUE_TOOTH_AUX_FUNC_ENABLE
#define BLUE_TOOTH_AUX_FUNC_GPIO_AT_P37

#endif
#endif


#ifdef JK_SM_001_1096A_V001

#define SYS_OSC_USE_ONCHIP_HTC
#define IIC_GPIO_CLK_DATA_USE_P01_P26
#define ADKEY_GPIO_USE_P07

#define MUTE_GPIO_USE_DUMMY

#define PLAY_STATUS_LED_P02
#define MUSIC_PLAY_STOP_MODE_ENABLE

#define NOT_DISPLAY_SCAN

#define DEV_PLUG_PLAY_DISABLE
#define DONT_SPARK_PLAY_LED_WHEN_PLAY

#define DISABLE_P05_OSC_OUTPUT
#define NOT_USE_LINE_IN_FUNC
#define RADIO_NEXT_PREV_STOP_SCAN

#define TWO_PLAY_STATUS_LED
#define PLAY_STATUS_ID2_LED_P27
#define PLAY_STATUS_LED_OFF_AT_DEV_INIT

#endif

//#endif


