
#define K1161_YJH_1161_1090B_V001

#ifdef K1161_YJH_1161_1090B_V001

//#define SYS_OSC_USE_ONCHIP_HTC

#define MUTE_GPIO_USE_P03

#define IIC_GPIO_CLK_DATA_USE_P00_P01
#define ADKEY_GPIO_USE_P06
#define CUSTOMER_DEFINED_ADKEY_RESISTOR

#define PLAY_STATUS_LED_P07

#define CUSTOM_DEFINED_PATH_AUX_AT_P24P25_RADIO_AT_P26P27

#define USE_POWER_KEY
#define POWER_CTRL_GPIO_USE_P02

#define USE_BAT_MANAGEMENT
#define CHARGER_DETECTION_THREAD_ENABLE
#define CHARGER_DETECT_USE_P17
#define BAT_LEVEL_LED_ICON_IND


#define OTP_MUSIC_FUNC_ENABLE
#define Lamborghini_voice

#define LED_GPIO_PORT_CUSTOMERIZED

#define RADIO_PLAY_KEY_MUTE_VOL
#define AUX_PLAY_KEY_MUTE_VOL
#define AUX_NEXT_PREV_ADJ_VOL

#define MUSIC_DISP_PAUSE_STR
#define RADIO_DISP_PAUSE_STR
#define AUX_DISP_PAUSE_STR

#define NO_DEVICE_DEFAULT_IDLE_MODE

#endif

